[tools]
bun = "1.3.3"
go = "1.25.4"
golangci-lint = "latest"
dprint = "latest"

[tasks.lint]
description = "Run all linters"
depends = ["lint:*"]

[tasks.fmt]
description = "Run all formatters"
depends = ["fmt:*"]
